# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'nightModeDemo' do
pod 'DKNightVersion', '~> 1.2'
end

target 'nightModeDemoTests' do

end

target 'nightModeDemoUITests' do

end

